name: download composer.phar

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 5 * *

jobs:
  getcomposer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install php
      run: |
        sudo apt-get update  -y
        sudo apt-get upgrade -y
        sudo apt-get install -y php
        php --version

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: get composer.phar
      id: getcomposer
      shell: bash
      run: |
        rm -fv composer.phar
        date=$(date '+%a %d %b %Y %X %P')
        echo "::set-output name=date::${date}"
        curl -sL 'https://getcomposer.org/download/' \
          | grep -A 5 -Fhi '<pre class="installer">' \
          | sed -Ee 's~<pre\sclass="installer">~\n~i;s~</pre>~\n~ig' \
          | head -n -1 \
          | bash -x
        echo -e '\r\n@php "%~dp0composer.phar" %* \r\n' > composer.bat
        echo -e '#!/usr/bin/env bash\n\nphp composer.phar "$@"\n' > composer.sh
        chmod u+x *.sh
        echo
        php --version
        echo
        bash composer.sh --version
        composer_version_short=$(bash composer.sh --version | tr ' ' '\n' | head -n 3 | tail -n 1)
        composer_version_long=$(bash composer.sh --version )
        echo "::set-output name=version1::${composer_version_short}"
        echo "::set-output name=version2::${composer_version_long}"
        git add composer.*
        git status
        ls -lah --group-directories-first
        echo ${composer_version_short}
        echo ${composer_version_long}
        echo ${date}
#        # ${{ steps.getcomposer.outputs.version1 }}

    - name: make pull request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        commit-message: get ${{ steps.getcomposer.outputs.version2 }}
        committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: true
        branch: get-composer-${{ steps.getcomposer.outputs.version1 }}
        delete-branch: true
        branch-suffix: timestamp
        title: get ${{ steps.getcomposer.outputs.version2 }} for ${{ steps.getcomposer.outputs.date }}
        body: |
          get ${{ steps.getcomposer.outputs.version2 }}
          
          action executed on ${{ steps.getcomposer.outputs.date }}
          
          Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}
